import { createClient } from '@supabase/supabase-js';

export const supabase = createClient('https://vhmldvbbqtjyjevclzch.supabase.co', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZobWxkdmJicXRqeWpldmNsemNoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY1NTAzNjcyOCwiZXhwIjoxOTcwNjEyNzI4fQ.cKHfXaUoT3EwiP9252xU5twO_I3aZkIikk_y7DLZa54')
